### PR TITLE
Array pathing

### LINKED ISSUE #6: Validate returns invalid `dataPath`
Given the following code:
```
const VALID_SHIFT_ITEM = {
  required: ['totalCapacity', 'start', 'end'],
  properties: {
    totalCapacity: {
      type: 'integer',
      minimum: 1,
      maximum: OPPORTUNITY_SHIFT_MAX_CAPACITY,
    },
    remainingCapacity: {
      type: 'integer',
      minimum: 0,
      maximum: { $data: '1/totalCapacity' },
    },
    start: {
      required: ['localDateTime', 'timeZone'],
      properties: {
        localDateTime: {
          localDateTime: true,
          moment: {
            "validate": [
              {
                "test": "isAfter",
                "value": {
                  "$data": "2/end/localDateTime"
                }
              }
            ]
          }
        },
        timeZone: { type: 'string', minLength: 1 },
      },
    },
    end: {
      required: ['localDateTime', 'timeZone'],
      properties: {
        localDateTime: {
          localDateTime: true,
        },
        timeZone: { type: 'string', minLength: 1 },
      },
    },
  }
}
```
I get the following error returned from `validate()`

image

Note that the value is located at the schema root and says `localDateTime'` when it should actually be `localDateTime` (sans apostrophe) nested like this: `shifts/items/start/localDateTime`. 

A deeper look reveals that the error messages yielded by your plugin is as follows:

image

Note the double-encoded value wrapped in apostrophes. 

I believe the main AJV library is now storing this at `it.errorPath`

When defining my own `inline` validation, I find `it.errorPath` returns the value that I believe is needed here

image

however the code is so difficult to follow, I can't find where this is being declared in the pre-compilation code in order to produce the compiled result found in the `ajv-keywords` library:

https://github.com/epoberezkin/ajv-keywords/blob/master/keywords/dot/_formatLimit.jst

### PR DESCRIPTION
**Pull request by bfeister**
This closes #7, as I've added breaking changes to `master` in my fork. Reverting those change.

FYI - this fixes the issue raised in (and closes #6) for me. given the schema and context I provided in the bug report. Also, all tests pass, though I'm not sure how robust they are or aren't.

### CODE REVIEW

**Comment by afrankel-sfdo** [comment]
@cludden fix looks good on our end, could we get a review/approval on this?

**Comment by cludden** [comment]
one fix: can you revert the version bump? this is handled by standard-version when it generates CHANGELOG.md

**Comment by bfeister** [comment]
Will do now, thank you sir

**Comment by bfeister** [comment]
@cludden reverted version bump

**Pull request merged**
